layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

bio: Hi! 👋 My name is Anushka. I study engineering to build things that will help humans and society. I will be interning at Bank of America as a Global Technology Analyst Intern remotely this summer. Please feel free to look around and contact me at any of the links above.

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
    behance: anushkasaxena1
    devpost: anushkasaxena2019
  # dribbble: your_username
    facebook: anushka.saxena.927543
  # hackerrank: your_username
    instagram: _anushkasaxena
  # keybase: your_username
    linkedin: anushka-saxena-b40aa2165
  # mastodon: your_username
    medium: coffeecoders
  # stackoverflow: your_user_id
  # telegram: your_username
    twitter: 3muchcoffee5me
  # unsplash: your_username
  # vk: your_username
    website: http://anushkasaxena.com
  # youtube: your_username

portfolio:
  - name: Henna Hands
    web_url: https://www.behance.net/gallery/97934663/hand-modeling
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/henna-hands.jpg?raw=true
    description: Designed henna designs on hand models in Rhino 6.0 and Grasshopper using surface modelling and analytical geometry
    height: 75
    width: 100

  - name: Pokemon LED Lamp
    web_url: https://asaxena2019.github.io/pokemon-lamp/
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/pokemon-lamp.JPG?raw=true
    description: Designed an LED laser engraved Pokemon themed lamp on SolidWorks and Arduino
    height: 100
    width: 150

  - name: Pac-Man 1.12
    web_url: https://asaxena2019.github.io/termproject/
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/term-project.png?raw=true
    description: Programmed in Python a spin-off of Pac-Man with path finding ghosts, randomly generated maps, and side-scrolling boards
    height: 100
    width: 150

  - name: Feed the Burghers
    web_url: https://docs.google.com/presentation/d/1WD4Hb7N7vrbzsyrK_hBfRJQ5uq1ur7qLLiQBVR0iSB8/edit#slide=id.g35f391192_00
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/ftb.png?raw=true
    description: Designed an app in MIT App Inventor to connect economically disadvantaged people in Pittsburgh to food sources. Won Best Social Hack at HackCMU 2019
    height: 64
    width: 64

  - name: Still
    web_url: http://still-okay.herokuapp.com/
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/PennApps.JPG?raw=true
    description: Created an app in XCode and website in HTMl, CSS, and Javascript that helps users deal with anxiety and stress for PennApps 2018
    height: 100
    width: 150

  - name: Modelling the Forecast of Solar Energetic Particle Events
    web_url: https://asaxena2019.github.io/Modelling-the-Forecast-of-Solar-Energetic-Particle-Events-Year-2/
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/sep.jpeg?raw=true
    description: Programmed a script in Java that forecasts the effects of solar phenomenon on Earth based on data from NASA satellites
    height: 70
    width: 75

experience:
  - name: Science Fair Department Intern @ GSMST
    web_url: https://sites.google.com/gsmst.org/gsmstsciengfair/home
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/gsmst.png?raw=true
    description: Senior Capstone Experience. Created this website that provided science fair resources and organized the school's annual science fair
    height: 64
    width: 64
  
  - name: Cisco High Extern @ Cisco
    web_url: https://docs.google.com/presentation/d/1JqSZuD8PwCzQ6aMYjNkSGibQtbI0a-70MrDjWdpORhU/edit#slide=id.g3d28bd4c0a_3_9
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/cisco.jpg?raw=true
    description: Designed solutions to solve Atlanta's transportation industry using Cisco Technology and presented in front of Cisco leadership
    height: 64
    width: 64

  - name: Research Assistant @ Department of Neurosurgery, Emory University
    web_url: https://drive.google.com/file/d/0BwsuRuLuuDNjV1AtRU91Skh6QUQwVXBoTGlWbDlTQjRoNnNn/view?usp=sharing
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/emory.jpg?raw=true
    description: Researched bioluminescent sources in marine animals to be used in optogenetic tools to solve neurotic illnesses such as epilepsy
    height: 64
    width: 64

  - name: Research Assistant @ David G. Lynn Group, Emory University
    web_url: https://docs.google.com/presentation/d/1oTsCLaj7-yhYdXtjtp273vPh7d7YVnFQqg8McCkQAQE/edit#slide=id.p13
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/emory.jpg?raw=true
    description: Researched dynamic chemical networks and their importance in organic chemistry
    height: 64
    width: 64

organizations:
  - name: ScottyLabs
    web_url: https://scottylabs.org/
    image_url: https://github.com/asaxena2019/asaxena2019.github.io/blob/master/_images/scotty-dog.jpeg?raw=true
    description: Director of Events of the tech entrepreneurial club at CMU. Help plan Web Dev Weekend, a series of web development workshops, and TartanHacks, CMU's largest hackathon
    height: 64
    width: 64

  - name: Robotics Club
    web_url: https://roboticsclub.org/
    image_url: https://avatars3.githubusercontent.com/u/5898082?s=280&v=4
    description: Current secretary of the robotics club at CMU. Part of the mentorship committee to plan educational activities for our underclassmen
    height: 64
    width: 64

events:
  - name: Women in Cybersecurity Conference 2020
    web_url: 
    image_url: https://infosec-conferences.com/wp-content/uploads/2019/11/logo-conference-wicys-v1.png
    description: Received a scholarship to attend this conference on cybersecurity but did not go due to COVID-19
    height: 100
    width: 200
  
  - name: Jane Street Women in STEM 2019
    web_url: https://www.linkedin.com/feed/update/urn:li:activity:6562450807134961664/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Jane_Street_Capital_Logo.svg/1200px-Jane_Street_Capital_Logo.svg.png
    description: Visited Jane Street and learned about quantitative trading among approximately 80 other freshman girls
    height: 75
    width: 100
  
  - name: National Center for Women and Information Technology
    web_url: https://www.aspirations.org/user/119641
    image_url: https://www.ncwit.org/sites/all/themes/ncwit/images/ncwit-logo-234.png
    description: Awarded NCWIT National Honorable Mention and Georgia Affiliate Winner for two years based on my achievements in computing and technology
    height: 64
    width: 64

  - name: Georgia Junior Science and Humanities Symposium Oral Presenter 2017
    web_url: https://drive.google.com/file/d/0BwsuRuLuuDNjV1AtRU91Skh6QUQwVXBoTGlWbDlTQjRoNnNn/view?usp=sharing
    image_url: https://www.georgiacenter.uga.edu/sites/default/files/jshs-logo.jpg
    description: Presented on my research from the Department of Neurosurgery at Emory on optogenetics research
    height: 75
    width: 75

  - name: Georgia Junior Science and Humanities Symposium Oral Presenter 2016
    web_url: https://drive.google.com/file/d/0BwsuRuLuuDNjaDlfU280blM4N2RqQ3NTUUJpczZmSkhUcHY4/view?usp=sharing
    image_url: https://www.georgiacenter.uga.edu/sites/default/files/jshs-logo.jpg
    description: Presented my data derived from NASA satellites on Coronal Mass Ejections year 1 and won best poster presenter
    height: 75
    width: 75

#topics:
 # - name: Full Stack
   # web_url:
   # image_url: 
   # description: To become a better web app developer. Currently using Youtube and Linkedin Learning as learning resources
   # height: 64
   # width: 64