# most of the editing will be done here

# to add favicon, upload image to repo and name it favicon.ico

layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

# If you want to include any social media, just uncomment and add username

#social_media:
  # behance: your_username
  # devpost: your_username
  # dribbble: your_username
    facebook: your_username
  # hackerrank: your_username
    instagram: your_username
  # keybase: your_username
    linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
    twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: your_username
  # youtube: your_username

portfolio:

# if you want to add mor languages, just add another "title" point underneath language
# be mindful of spacing

  - name: insert name here
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to the image repo, pushing repo to Github, then linking pictures from remote repo to local repo. Will be resolving this issue soon
    image_url: 
    description: insert description here
    #give height and width of picture as desired by pixels
    height: 
    width: 
    language:
      - title: HTML/CSS
      - title: JavaScript
      - title: and many more
    date: insert date here

#example
  - name: Github
    web_url: https://github.com/
    image_url: https://github.githubassets.com/images/modules/logos_page/Octocat.png
    description: Access code from around the world!
    height: 64
    width: 64
    language:
      - title: HTML/CSS
      - title: JavaScript
      - title: and many more
    date: 2008 - Present

#you can add as many cards as you like!

experience:
  - name: insert name here
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: 
    description: insert description here
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date:

organizations:
  - name: insert name here
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: 
    description: insert description here
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: 

events:
-   name: insert name here
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: 
    description: insert description here
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: 

topics:
  - name: insert name here
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: 
    description: insert description here
    #give height and width of picture as desired by pixels
    height:
    width: